Fix typo for accents
T3kstiil3/SoundTouch-Chrome-Extension pull request #22
Opened 2020-10-08 19:37 UTC by Ramiellll

2020-10-08 19:40 UTC, Ramiellll commented
Fixed bug #14

2020-10-26 19:44 UTC, T3kstiil3 requested changes

2020-10-26 19:44 UTC, T3kstiil3 commented on index.html
> +    <meta http-equiv="content-type" content="text/html; charset="utf-8" />
Not sure this will be fix the problem and there is a syntax error on 
```
content="text/html; charset="utf-8"
```

2022-08-02 16:46 UTC, AurelienLoyer approved these changes

2022-08-02 16:46 UTC, merged